services:
  frontend:
    build:
      context: frontend/
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: backend/
    ports:
      - '3001:5000'
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgres://postgres@db:5432/hfh_dev

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: hfh_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
