"""add asic

Create Date: 2024-05-05 08:00:02.919423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1714896002'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=40)),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_address'), 'asic', ['address'], unique=False)
    op.create_index(op.f('ix_asic_name'), 'asic', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asic_name'), table_name='asic')
    op.drop_index(op.f('ix_asic_address'), table_name='asic')
    op.drop_table('asic')
    # ### end Alembic commands ###
